import apolloServerExpress from './apolloServerExpress.png';
import bcrypt from './bcrypt.png';
import codeQuiz from './codeQuiz.png';
import css from './css.png';
import dotenv from './dotenv.png';
import employeeTracker from './employeeTracker.gif';
import express from './express.png';
import fullCalendar from './fullCalendar.png';
import github from './github.png';
import googleMaps from './googleMaps.png';
import graphQL from './graphQL.png';
import handlebars from './handlebars.png';
import html from './html.png';
import JavaScript from './JavaScript.png';
import jwt from './jwt.png';
import mealMappr from './mealMappr.png';
import mongoose from './mongoose.png';
import muiMateral from './muiMaterial.png';
import nodeJs from './nodeJs.png';
import nodeMailer from './nodeMailer.png';
import reactJs from './reactJs.png';
import reactRouter from './reactRouter.png';
import tailwindCss from './tailwindCss.png';
import yardGems from './yardGems.png';

export default { apolloServerExpress, bcrypt, codeQuiz, css, dotenv, employeeTracker, express, fullCalendar, github, googleMaps, graphQL, handlebars, html, JavaScript, jwt, mealMappr, mongoose, muiMateral, nodeJs, nodeMailer, reactJs, reactRouter, tailwindCss, yardGems };
